name: "Merge Rancher installer manifest"
description: "Merge Rancher installer docker arch specific images manifest"
runs:
  using: "composite"
  steps:
    - name: Setup Environment Variables
      uses: ./.github/actions/setup-tag-env
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository_owner }}/system-agent-installer-rancher
        flavor: |
          latest=false
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
        registry: ${{ env.REGISTRY }}
    - name: Create manifest list and push
      shell: bash
      run: |
        docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/system-agent-installer-rancher:${{ env.TAG }} ${{ env.REGISTRY }}/${{ github.repository_owner }}/system-agent-installer-rancher:${{ env.TAG }}-amd64 ${{ env.REGISTRY }}/${{ github.repository_owner }}/system-agent-installer-rancher:${{ env.TAG }}-arm64
        if [[ "${{ github.ref_name }}" == release/v* ]]; then
          docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/system-agent-installer-rancher:${{ env.HEAD_TAG }} ${{ env.REGISTRY }}/${{ github.repository_owner }}/system-agent-installer-rancher:${{ env.TAG }}-amd64 ${{ env.REGISTRY }}/${{ github.repository_owner }}/system-agent-installer-rancher:${{ env.TAG }}-arm64
        fi
    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ github.repository_owner }}/system-agent-installer-rancher:${{ env.TAG }}
