// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../../pkg/peermanager/peermanager.go
//
// Generated by this command:
//
//	mockgen -package usercontrollers -source=../../../../pkg/peermanager/peermanager.go -destination=./peermanager_mock_test.go
//

// Package usercontrollers is a generated GoMock package.
package usercontrollers

import (
	reflect "reflect"

	peermanager "github.com/rancher/rancher/pkg/peermanager"
	gomock "go.uber.org/mock/gomock"
)

// MockPeerManager is a mock of PeerManager interface.
type MockPeerManager struct {
	ctrl     *gomock.Controller
	recorder *MockPeerManagerMockRecorder
	isgomock struct{}
}

// MockPeerManagerMockRecorder is the mock recorder for MockPeerManager.
type MockPeerManagerMockRecorder struct {
	mock *MockPeerManager
}

// NewMockPeerManager creates a new mock instance.
func NewMockPeerManager(ctrl *gomock.Controller) *MockPeerManager {
	mock := &MockPeerManager{ctrl: ctrl}
	mock.recorder = &MockPeerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerManager) EXPECT() *MockPeerManagerMockRecorder {
	return m.recorder
}

// AddListener mocks base method.
func (m *MockPeerManager) AddListener(l chan<- peermanager.Peers) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddListener", l)
}

// AddListener indicates an expected call of AddListener.
func (mr *MockPeerManagerMockRecorder) AddListener(l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddListener", reflect.TypeOf((*MockPeerManager)(nil).AddListener), l)
}

// IsLeader mocks base method.
func (m *MockPeerManager) IsLeader() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLeader")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLeader indicates an expected call of IsLeader.
func (mr *MockPeerManagerMockRecorder) IsLeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLeader", reflect.TypeOf((*MockPeerManager)(nil).IsLeader))
}

// Leader mocks base method.
func (m *MockPeerManager) Leader() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Leader")
}

// Leader indicates an expected call of Leader.
func (mr *MockPeerManagerMockRecorder) Leader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leader", reflect.TypeOf((*MockPeerManager)(nil).Leader))
}

// RemoveListener mocks base method.
func (m *MockPeerManager) RemoveListener(l chan<- peermanager.Peers) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveListener", l)
}

// RemoveListener indicates an expected call of RemoveListener.
func (mr *MockPeerManagerMockRecorder) RemoveListener(l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveListener", reflect.TypeOf((*MockPeerManager)(nil).RemoveListener), l)
}
