name: "Merge Rancher agent manifest"
description: "Merge Rancher agent docker arch specific images manifest"
runs:
  using: "composite"
  steps:
    - name: Setup Environment Variables
      uses: ./.github/actions/setup-tag-env
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
        registry: ${{ env.REGISTRY }}
    - name: Create manifest list and push
      shell: bash
      run: |
        # docker buildx imagetools create pushes to the registry by default, which is not the same behavior as docker manifest create
        docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }} \
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-amd64 \
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-arm64

        if [[ "${{ github.ref_name }}" == release/v* ]] || [[ "${{ github.ref_name }}" == "main" ]]; then
          docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher-agent:${{ env.HEAD_TAG }} \
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-amd64 \
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-arm64
        fi


