name: "Install yq"
description: "Install yq from source"
inputs:
  version:
    description: "yq version"
    default: v4.45.1
  arch:
    description: "host arch"
    required: true
  use-sudo:
    description: "use sudo to move the yq binary"
    default: false
runs:
  using: "composite"
  steps:
    - name: install yq
      shell: bash
      run: |
        curl -fsL https://github.com/mikefarah/yq/releases/download/${{ inputs.version }}/yq_linux_${{ inputs.arch }}.tar.gz | tar xz
        mv_cmd="mv"
        ${{ inputs.use-sudo && 'sudo' || '' }} mv yq_linux_${{ inputs.arch }} /usr/bin/yq

