variable vsphere_user {}
variable vsphere_password {}
variable vsphere_server {}
variable vsphere_datacenter {}
variable vsphere_datastore {}
variable vsphere_resource_pool {}
variable vsphere_host {}
variable vsphere_network {}
variable vsphere_template {}
variable vsphere_folder {}
variable cattle_token {}
variable cattle_url {}
variable monitoring_version {}
variable istio_version {}
variable logging_version {}
variable cluster_name {}
variable node_name {}
variable ssh_key_path {}
variable minio_ca {}
variable minio_endpoint {}
variable minio_access_key {}
variable minio_secret_key {}
variable minio_bucket {}