---
kind: pipeline
name: testing-windows

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: docker  
  pull: always
  image: orstar/dapper:v0.4.1-windows-1809
  settings:
    daemon_off: true
    dry_run: true
    dockerfile: docker/Dockerfile.windows.1809
    repo: loganhz/test
    tags: latest
  volumes:
  - name: docker_pipe
    path: //./pipe/docker_engine

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"
...