webhookVersion: 106.0.1+up0.7.1
remoteDialerProxyVersion: 106.0.0+up0.4.4
provisioningCAPIVersion: 106.0.0+up0.7.0
cspAdapterMinVersion: 106.0.0+up6.0.0
defaultShellVersion: rancher/shell:v0.4.1-rc.2
fleetVersion: 106.1.1+up0.12.3-beta.1
