webhookVersion: 107.0.8+up0.8.9
remoteDialerProxyVersion: 106.0.2+up0.5.1
provisioningCAPIVersion: 107.0.0+up0.8.0
cspAdapterMinVersion: 107.0.0+up7.0.0
defaultShellVersion: rancher/shell:v0.5.3
fleetVersion: 107.0.15+up0.13.15
defaultSccOperatorImage: rancher/scc-operator:v0.5.1-rc.3
chartAuditLogImage: rancher/mirrored-bci-micro:15.6.24.2
