webhookVersion: 107.0.0+up0.8.0-rc.12
remoteDialerProxyVersion: 106.0.0+up0.4.4
provisioningCAPIVersion: 107.0.0+up0.8.0
cspAdapterMinVersion: 107.0.0+up7.0.0-rc.1
defaultShellVersion: rancher/shell:v0.5.0-rc.4
fleetVersion: 107.0.0+up0.13.0-beta.4
