webhookVersion: 108.0.0+up0.9.0-rc.8
remoteDialerProxyVersion: 106.0.2+up0.6.0-rc.4
provisioningCAPIVersion: 107.0.0+up0.8.0
turtlesVersion: 108.0.0+up0.25.0-rc.2
cspAdapterMinVersion: 107.0.0+up7.0.0-rc.1
defaultShellVersion: rancher/shell:v0.5.0
fleetVersion: 108.0.0+up0.14.0-alpha.4
defaultSccOperatorImage: rancher/scc-operator:head
