webhookVersion: 106.0.3+up0.7.3-rc.2
remoteDialerProxyVersion: 106.0.0+up0.4.4
provisioningCAPIVersion: 106.0.0+up0.7.0
cspAdapterMinVersion: 106.0.0+up6.0.0
defaultShellVersion: rancher/shell:v0.4.1
fleetVersion: 106.1.2+up0.12.4-rc.3
