webhookVersion: 107.0.0+up0.8.0
remoteDialerProxyVersion: 106.0.1+up0.5.0
provisioningCAPIVersion: 107.0.0+up0.8.0
cspAdapterMinVersion: 107.0.0+up7.0.0
defaultShellVersion: rancher/shell:v0.5.0
fleetVersion: 107.0.1+up0.13.1-rc.2
defaultSccOperatorImage: rancher/scc-operator:v0.0.0-alpha.6
