webhookVersion: 106.0.0+up0.7.0-rc.9
remoteDialerProxyVersion: 106.0.0+up0.4.4-rc.2
provisioningCAPIVersion: 106.0.0+up0.7.0
cspAdapterMinVersion: 106.0.0+up6.0.0-rc1
defaultShellVersion: rancher/shell:v0.4.0
fleetVersion: 106.0.0+up0.12.0-rc.1
