webhookVersion: 109.0.0+up0.10.0-rc.9
remoteDialerProxyVersion: 109.0.0+up0.7.0-rc.4
provisioningCAPIVersion: 108.0.0+up0.9.0
turtlesVersion: 109.0.0+up0.26.0-rc.1
cspAdapterMinVersion: 108.0.0+up8.0.0
defaultShellVersion: rancher/shell:v0.6.2-rc.1
fleetVersion: 109.0.0+up0.15.0-alpha.10
defaultSccOperatorImage: rancher/scc-operator:v0.3.1-rc.2
# NOTE: when updating this version, you will also need to update the hardcoded
# k8s minor <-> image tag mapping in pkg/controllers/capr/autoscaler/fleet.go (imageTagVersions variable).
# if adding support for a new k8s minor release (e.g. new rancher release)
clusterAutoscalerChartVersion: 9.50.1
