webhookVersion: 108.0.0+up0.9.0-rc.4
remoteDialerProxyVersion: 106.0.1+up0.5.0
provisioningCAPIVersion: 107.0.0+up0.8.0
cspAdapterMinVersion: 107.0.0+up7.0.0-rc.1
defaultShellVersion: rancher/shell:v0.5.0
fleetVersion: 107.0.0+up0.13.0
defaultSccOperatorImage: rancher/scc-operator:head
