webhookVersion: 107.0.4+up0.8.4
remoteDialerProxyVersion: 106.0.1+up0.5.0
provisioningCAPIVersion: 107.0.0+up0.8.0
cspAdapterMinVersion: 107.0.0+up7.0.0
defaultShellVersion: rancher/shell:v0.5.1
fleetVersion: 107.0.7+up0.13.7-alpha.2
defaultSccOperatorImage: rancher/scc-operator:v0.3.1
