webhookVersion: 106.0.11+up0.7.11-rc.1
remoteDialerProxyVersion: 106.0.2+up0.4.6-rc.1
provisioningCAPIVersion: 106.0.0+up0.7.0
cspAdapterMinVersion: 106.0.1+up6.0.1
defaultShellVersion: rancher/shell:v0.4.4
fleetVersion: 106.1.17+up0.12.19
