webhookVersion: 106.0.8+up0.7.8-rc.1
remoteDialerProxyVersion: 106.0.0+up0.4.4
provisioningCAPIVersion: 106.0.0+up0.7.0
cspAdapterMinVersion: 106.0.0+up6.0.0
defaultShellVersion: rancher/shell:v0.4.2-rc.1
fleetVersion: 106.1.7+up0.12.9-beta.2
