name: "Notify a release using a Slack Webhook"
description: "Use a slack webhook to send release information"
inputs:
  tag:
    type: "string"
    default: "${{ github.ref_name }}"
  status:
    type: "string"
    default: "Completed ✅"
  commit_url:
    type: "string"
    default: "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
  workflow_url:
    type: "string"
    default: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
runs:
  using: "composite"
  steps:
    - name: Send notification
      env:
        TAG: ${{ inputs.tag }}
        STATUS: ${{ inputs.status }}
        COMMIT_URL: ${{ inputs.commit_url }}
        WORKFLOW_URL: ${{ inputs.workflow_url }}
      shell: bash
      run: |
        curl -X POST "${{ env.WEBHOOK_URL }}" -d '{"tag": "${{ env.TAG }}","status": "${{ env.STATUS }}","commit_url": "${{ env.COMMIT_URL }}","workflow_url": "${{ env.WORKFLOW_URL }}"}'
