{{- /*
These Secrets and the ConfigMap are only intended to be used the first time Rancher is installed.
This is a workaround for when the scc.cattle.io CRDs may not (almost always won't) be installed
when the helm chart is installed. After that time, users should use the CRDs - potentially this chart should if they are there?
*/}}
{{- if and .Values.registration.enabled .Values.registration.regCode }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-scc-system
  annotations:
    "helm.sh/resource-policy": keep
---
apiVersion: v1
kind: Secret
metadata:
  name: "scc-registration"
  namespace: "cattle-scc-system"
  annotations:
    "helm.sh/resource-policy": keep
  labels: {{ include "rancher.labels" . | nindent 4 }}{{ include "rancher.commonLabels" (dict "context" . "partOf" "rancher") | indent 4 }}
type: Opaque
data:
  regCode: {{ .Values.registration.regCode | b64enc }}
  mode: {{ default "online" .Values.registration.mode }}
{{- if .Values.registration.registrationEndpointURL }}
  registrationEndpointURL: {{ .Values.registration.registrationEndpointURL | quote }}
{{- end }}
{{ end -}}