apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "rancher.fullname" . }}
  labels:
{{ include "rancher.labels" . | indent 4 }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
  {{- if not (default .Values.service.disableHTTP false) }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
    {{- if .Values.service.nodePortHttps }}
    nodePort: {{ .Values.service.nodePortHttps }}
    {{- else if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  {{- else }}
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
    {{- if .Values.service.nodePortHttps }}
    nodePort: {{ .Values.service.nodePortHttps }}
    {{- else if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  {{- end }}
  {{- else }}
  ports:
  {{- if not (default .Values.service.disableHTTP false) }}
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  {{- end }}
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  {{- end }}
  selector:
    app: {{ template "rancher.fullname" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "rancher.fullname" . }}-internal
  labels:
{{ include "rancher.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 444
      protocol: TCP
      name: https-internal
  selector:
    app: {{ template "rancher.fullname" . }}
