name: "Publish images files to aws"
description: "Upload images files to an s3 bucket"
runs:
  using: "composite"
  steps:
    - name: Upload artifacts
      shell: bash
      run: |
        set -ex
        source scripts/artifacts-list.sh

        for artifact in "${ARTIFACTS_WITH_CHECKSUM[@]}"; do
          aws s3 cp "./${ARTIFACTS_BASE_DIR}/${artifact}" "s3://${ARTIFACTS_BUCKET_NAME}/rancher/${TAG}/${artifact}"
        done
