name: "Build Rancher Installer"
description: "Build and upload the Rancher installer image"
runs:
  using: "composite"
  steps:
    - name: Environment variables
      shell: bash
      run: |
        if [[ "$ARCH" == "x64" ]]; then
          echo "ARCH=amd64" >> $GITHUB_ENV
        fi
    - name: Setup Environment Variables
      uses: ./.github/actions/setup-tag-env
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/system-agent-installer-rancher
        flavor: |
          latest=false
    - name: Login to Docker Registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
        registry: ${{ env.REGISTRY }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
    - name: Build and export agent
      id: build
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
      with:
        push:  true
        build-args: |
          "VERSION=${{ env.TAG }}"
          "ARCH=${{ matrix.arch }}"
        tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/system-agent-installer-rancher:${{ env.TAG }}-${{ env.ARCH }}
        context: .
        platforms: "${{ env.OS }}/${{ env.ARCH }}"
        file: ./package/Dockerfile.installer
        labels: "${{ steps.meta.outputs.labels }}"
