// Copyright The Helm Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: rancher_helmv2/hook.proto

package helmv2api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hook_Event int32

const (
	Hook_UNKNOWN              Hook_Event = 0
	Hook_PRE_INSTALL          Hook_Event = 1
	Hook_POST_INSTALL         Hook_Event = 2
	Hook_PRE_DELETE           Hook_Event = 3
	Hook_POST_DELETE          Hook_Event = 4
	Hook_PRE_UPGRADE          Hook_Event = 5
	Hook_POST_UPGRADE         Hook_Event = 6
	Hook_PRE_ROLLBACK         Hook_Event = 7
	Hook_POST_ROLLBACK        Hook_Event = 8
	Hook_RELEASE_TEST_SUCCESS Hook_Event = 9
	Hook_RELEASE_TEST_FAILURE Hook_Event = 10
	Hook_CRD_INSTALL          Hook_Event = 11
)

// Enum value maps for Hook_Event.
var (
	Hook_Event_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "PRE_INSTALL",
		2:  "POST_INSTALL",
		3:  "PRE_DELETE",
		4:  "POST_DELETE",
		5:  "PRE_UPGRADE",
		6:  "POST_UPGRADE",
		7:  "PRE_ROLLBACK",
		8:  "POST_ROLLBACK",
		9:  "RELEASE_TEST_SUCCESS",
		10: "RELEASE_TEST_FAILURE",
		11: "CRD_INSTALL",
	}
	Hook_Event_value = map[string]int32{
		"UNKNOWN":              0,
		"PRE_INSTALL":          1,
		"POST_INSTALL":         2,
		"PRE_DELETE":           3,
		"POST_DELETE":          4,
		"PRE_UPGRADE":          5,
		"POST_UPGRADE":         6,
		"PRE_ROLLBACK":         7,
		"POST_ROLLBACK":        8,
		"RELEASE_TEST_SUCCESS": 9,
		"RELEASE_TEST_FAILURE": 10,
		"CRD_INSTALL":          11,
	}
)

func (x Hook_Event) Enum() *Hook_Event {
	p := new(Hook_Event)
	*p = x
	return p
}

func (x Hook_Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hook_Event) Descriptor() protoreflect.EnumDescriptor {
	return file_rancher_helmv2_hook_proto_enumTypes[0].Descriptor()
}

func (Hook_Event) Type() protoreflect.EnumType {
	return &file_rancher_helmv2_hook_proto_enumTypes[0]
}

func (x Hook_Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hook_Event.Descriptor instead.
func (Hook_Event) EnumDescriptor() ([]byte, []int) {
	return file_rancher_helmv2_hook_proto_rawDescGZIP(), []int{0, 0}
}

type Hook_DeletePolicy int32

const (
	Hook_SUCCEEDED            Hook_DeletePolicy = 0
	Hook_FAILED               Hook_DeletePolicy = 1
	Hook_BEFORE_HOOK_CREATION Hook_DeletePolicy = 2
)

// Enum value maps for Hook_DeletePolicy.
var (
	Hook_DeletePolicy_name = map[int32]string{
		0: "SUCCEEDED",
		1: "FAILED",
		2: "BEFORE_HOOK_CREATION",
	}
	Hook_DeletePolicy_value = map[string]int32{
		"SUCCEEDED":            0,
		"FAILED":               1,
		"BEFORE_HOOK_CREATION": 2,
	}
)

func (x Hook_DeletePolicy) Enum() *Hook_DeletePolicy {
	p := new(Hook_DeletePolicy)
	*p = x
	return p
}

func (x Hook_DeletePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hook_DeletePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_rancher_helmv2_hook_proto_enumTypes[1].Descriptor()
}

func (Hook_DeletePolicy) Type() protoreflect.EnumType {
	return &file_rancher_helmv2_hook_proto_enumTypes[1]
}

func (x Hook_DeletePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hook_DeletePolicy.Descriptor instead.
func (Hook_DeletePolicy) EnumDescriptor() ([]byte, []int) {
	return file_rancher_helmv2_hook_proto_rawDescGZIP(), []int{0, 1}
}

// Hook defines a hook object.
type Hook struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Kind is the Kubernetes kind.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Path is the chart-relative path to the template.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Manifest is the manifest contents.
	Manifest string `protobuf:"bytes,4,opt,name=manifest,proto3" json:"manifest,omitempty"`
	// Events are the events that this hook fires on.
	Events []Hook_Event `protobuf:"varint,5,rep,packed,name=events,proto3,enum=rancher.legacytypes.helmv2api.Hook_Event" json:"events,omitempty"`
	// LastRun indicates the date/time this was last run.
	LastRun *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	// Weight indicates the sort order for execution among similar Hook type
	Weight int32 `protobuf:"varint,7,opt,name=weight,proto3" json:"weight,omitempty"`
	// DeletePolicies are the policies that indicate when to delete the hook
	DeletePolicies []Hook_DeletePolicy `protobuf:"varint,8,rep,packed,name=delete_policies,json=deletePolicies,proto3,enum=rancher.legacytypes.helmv2api.Hook_DeletePolicy" json:"delete_policies,omitempty"`
	// DeleteTimeout indicates how long to wait for a resource to be deleted before timing out
	DeleteTimeout int64 `protobuf:"varint,9,opt,name=delete_timeout,json=deleteTimeout,proto3" json:"delete_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hook) Reset() {
	*x = Hook{}
	mi := &file_rancher_helmv2_hook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hook) ProtoMessage() {}

func (x *Hook) ProtoReflect() protoreflect.Message {
	mi := &file_rancher_helmv2_hook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hook.ProtoReflect.Descriptor instead.
func (*Hook) Descriptor() ([]byte, []int) {
	return file_rancher_helmv2_hook_proto_rawDescGZIP(), []int{0}
}

func (x *Hook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hook) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Hook) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Hook) GetManifest() string {
	if x != nil {
		return x.Manifest
	}
	return ""
}

func (x *Hook) GetEvents() []Hook_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Hook) GetLastRun() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRun
	}
	return nil
}

func (x *Hook) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Hook) GetDeletePolicies() []Hook_DeletePolicy {
	if x != nil {
		return x.DeletePolicies
	}
	return nil
}

func (x *Hook) GetDeleteTimeout() int64 {
	if x != nil {
		return x.DeleteTimeout
	}
	return 0
}

var File_rancher_helmv2_hook_proto protoreflect.FileDescriptor

const file_rancher_helmv2_hook_proto_rawDesc = "" +
	"\n" +
	"\x19rancher_helmv2/hook.proto\x12\x1drancher.legacytypes.helmv2api\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x05\n" +
	"\x04Hook\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\bmanifest\x18\x04 \x01(\tR\bmanifest\x12A\n" +
	"\x06events\x18\x05 \x03(\x0e2).rancher.legacytypes.helmv2api.Hook.EventR\x06events\x125\n" +
	"\blast_run\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\alastRun\x12\x16\n" +
	"\x06weight\x18\a \x01(\x05R\x06weight\x12Y\n" +
	"\x0fdelete_policies\x18\b \x03(\x0e20.rancher.legacytypes.helmv2api.Hook.DeletePolicyR\x0edeletePolicies\x12%\n" +
	"\x0edelete_timeout\x18\t \x01(\x03R\rdeleteTimeout\"\xe5\x01\n" +
	"\x05Event\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vPRE_INSTALL\x10\x01\x12\x10\n" +
	"\fPOST_INSTALL\x10\x02\x12\x0e\n" +
	"\n" +
	"PRE_DELETE\x10\x03\x12\x0f\n" +
	"\vPOST_DELETE\x10\x04\x12\x0f\n" +
	"\vPRE_UPGRADE\x10\x05\x12\x10\n" +
	"\fPOST_UPGRADE\x10\x06\x12\x10\n" +
	"\fPRE_ROLLBACK\x10\a\x12\x11\n" +
	"\rPOST_ROLLBACK\x10\b\x12\x18\n" +
	"\x14RELEASE_TEST_SUCCESS\x10\t\x12\x18\n" +
	"\x14RELEASE_TEST_FAILURE\x10\n" +
	"\x12\x0f\n" +
	"\vCRD_INSTALL\x10\v\"C\n" +
	"\fDeletePolicy\x12\r\n" +
	"\tSUCCEEDED\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\x12\x18\n" +
	"\x14BEFORE_HOOK_CREATION\x10\x02BIZGgithub.com/rancher/rancher/pkg/catalogv2/internal/legacytypes/helmv2apib\x06proto3"

var (
	file_rancher_helmv2_hook_proto_rawDescOnce sync.Once
	file_rancher_helmv2_hook_proto_rawDescData []byte
)

func file_rancher_helmv2_hook_proto_rawDescGZIP() []byte {
	file_rancher_helmv2_hook_proto_rawDescOnce.Do(func() {
		file_rancher_helmv2_hook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rancher_helmv2_hook_proto_rawDesc), len(file_rancher_helmv2_hook_proto_rawDesc)))
	})
	return file_rancher_helmv2_hook_proto_rawDescData
}

var file_rancher_helmv2_hook_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rancher_helmv2_hook_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rancher_helmv2_hook_proto_goTypes = []any{
	(Hook_Event)(0),               // 0: rancher.legacytypes.helmv2api.Hook.Event
	(Hook_DeletePolicy)(0),        // 1: rancher.legacytypes.helmv2api.Hook.DeletePolicy
	(*Hook)(nil),                  // 2: rancher.legacytypes.helmv2api.Hook
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_rancher_helmv2_hook_proto_depIdxs = []int32{
	0, // 0: rancher.legacytypes.helmv2api.Hook.events:type_name -> rancher.legacytypes.helmv2api.Hook.Event
	3, // 1: rancher.legacytypes.helmv2api.Hook.last_run:type_name -> google.protobuf.Timestamp
	1, // 2: rancher.legacytypes.helmv2api.Hook.delete_policies:type_name -> rancher.legacytypes.helmv2api.Hook.DeletePolicy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rancher_helmv2_hook_proto_init() }
func file_rancher_helmv2_hook_proto_init() {
	if File_rancher_helmv2_hook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rancher_helmv2_hook_proto_rawDesc), len(file_rancher_helmv2_hook_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rancher_helmv2_hook_proto_goTypes,
		DependencyIndexes: file_rancher_helmv2_hook_proto_depIdxs,
		EnumInfos:         file_rancher_helmv2_hook_proto_enumTypes,
		MessageInfos:      file_rancher_helmv2_hook_proto_msgTypes,
	}.Build()
	File_rancher_helmv2_hook_proto = out.File
	file_rancher_helmv2_hook_proto_goTypes = nil
	file_rancher_helmv2_hook_proto_depIdxs = nil
}
