name: "Generate images files"
description: "Setup and generate images files"
runs:
  using: "composite"
  steps:
    - name: install dependencies
      shell: bash
      run: zypper install -y aws-cli jq awk
    - name: Setup Environment Variables
      uses: ./.github/actions/setup-tag-env
    - id: env
      name: Setup Dependencies Env Variables
      uses: ./.github/actions/setup-build-env
    - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version: '${{ steps.env.outputs.GO_VERSION }}'
        cache: ${{ github.event_name == 'pull_request' }}
    - name: Download data.json
      shell: bash
      run: |
        mkdir -p "$ARTIFACTS_BASE_DIR"
        curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${{ steps.env.outputs.CATTLE_KDM_BRANCH }}/data.json > "./$ARTIFACTS_BASE_DIR/data.json"
        cp "./$ARTIFACTS_BASE_DIR/data.json" "./$ARTIFACTS_BASE_DIR/rancher-data.json"
    - name: Create components and images files
      shell: bash
      env:
        REGISTRY: ""
      run: ./scripts/create-components-images-files.sh
    - name: Generate sha256sum
      shell: bash
      env:
        ARTIFACTS_TYPE: "components"
      run: scripts/artifacts-hashes.sh
