name: "Setup Dependencies Variables"
description: "Setup Dependencies Variables from other files"
inputs:
  rancher_path:
    description: "Path to the Rancher repository"
    required: true
    default: "."
outputs:
  CATTLE_KDM_BRANCH:
    description: "CATTLE_KDM_BRANCH from package/Dockerfile"
    value: ${{ steps.vars.outputs.CATTLE_KDM_BRANCH }} 
  CATTLE_K3S_VERSION: 
    description: "CATTLE_K3S_VERSION from package/Dockerfile"
    value: ${{ steps.vars.outputs.CATTLE_K3S_VERSION }}
  HELM_VERSION: 
    description: "HELM_VERSION from package/Dockerfile.installer"
    value: ${{ steps.vars.outputs.HELM_VERSION }}
  CATTLE_HELM_VERSION: 
    description: "CATTLE_HELM_VERSION from package/Dockerfile"
    value: ${{ steps.vars.outputs.CATTLE_HELM_VERSION }}
  GO_VERSION: 
    description: "GO_VERSION from package/Dockerfile"
    value: ${{ steps.vars.outputs.GO_VERSION }}
  HELM_UNITTEST_VERSION: 
    description: "HELM_UNITTEST_VERSION from Dockerfile.dapper"
    value: ${{ steps.vars.outputs.HELM_UNITTEST_VERSION }}
  CATTLE_RANCHER_WEBHOOK_VERSION: 
    description: "CATTLE_RANCHER_WEBHOOK_VERSION from scripts/package-env"
    value: ${{ steps.vars.outputs.CATTLE_RANCHER_WEBHOOK_VERSION }}
  CATTLE_REMOTEDIALER_PROXY_VERSION: 
    description: "CATTLE_REMOTEDIALER_PROXY_VERSION from scripts/package-env"
    value: ${{ steps.vars.outputs.CATTLE_REMOTEDIALER_PROXY_VERSION }} 
  CATTLE_RANCHER_PROVISIONING_CAPI_VERSION:
    description: "CATTLE_RANCHER_PROVISIONING_CAPI_VERSION from scripts/package-env"
    value: ${{ steps.vars.outputs.CATTLE_RANCHER_PROVISIONING_CAPI_VERSION }}
  CATTLE_RANCHER_TURTLES_VERSION:
    description: "CATTLE_RANCHER_TURTLES_VERSION from scripts/package-env"
    value: ${{ steps.vars.outputs.CATTLE_RANCHER_TURTLES_VERSION }}
  CATTLE_CSP_ADAPTER_MIN_VERSION: 
    description: "CATTLE_CSP_ADAPTER_MIN_VERSION from scripts/package-env"
    value: ${{ steps.vars.outputs.CATTLE_CSP_ADAPTER_MIN_VERSION }}
  CATTLE_FLEET_VERSION: 
    description: "CATTLE_FLEET_VERSION from scripts/package-env"
    value: ${{ steps.vars.outputs.CATTLE_FLEET_VERSION }}
runs:
  using: "composite"
  steps:
    - id: vars
      shell: bash
      run: |
        cd ${{ inputs.rancher_path }}
        source scripts/package-env

        echo "CATTLE_KDM_BRANCH=$CATTLE_KDM_BRANCH" >> $GITHUB_OUTPUT
        echo "CATTLE_K3S_VERSION=$CATTLE_K3S_VERSION" >> $GITHUB_OUTPUT 
        echo "HELM_VERSION=$HELM_VERSION" >> $GITHUB_OUTPUT 
        echo "GO_VERSION=$GO_VERSION" >> $GITHUB_OUTPUT
        echo "HELM_UNITTEST_VERSION=$HELM_UNITTEST_VERSION" >> $GITHUB_OUTPUT
        echo "CATTLE_RANCHER_WEBHOOK_VERSION=$CATTLE_RANCHER_WEBHOOK_VERSION" >> $GITHUB_OUTPUT 
        echo "CATTLE_REMOTEDIALER_PROXY_VERSION=$CATTLE_REMOTEDIALER_PROXY_VERSION" >> $GITHUB_OUTPUT 
        echo "CATTLE_RANCHER_PROVISIONING_CAPI_VERSION=$CATTLE_RANCHER_PROVISIONING_CAPI_VERSION" >> $GITHUB_OUTPUT
        echo "CATTLE_RANCHER_TURTLES_VERSION=$CATTLE_RANCHER_TURTLES_VERSION" >> $GITHUB_OUTPUT
        echo "CATTLE_CSP_ADAPTER_MIN_VERSION=$CATTLE_CSP_ADAPTER_MIN_VERSION" >> $GITHUB_OUTPUT 
        echo "CATTLE_FLEET_VERSION=$CATTLE_FLEET_VERSION" >> $GITHUB_OUTPUT 
        echo "CATTLE_HELM_VERSION=$CATTLE_HELM_VERSION" >> $GITHUB_OUTPUT
