FROM golang:1.16

# Configure Go
ENV GOPATH /go
ENV PATH ${PATH}:/go/bin

ENV WORKSPACE ${GOPATH}/src/github.com/rancher/rancher

WORKDIR $WORKSPACE/tests/v2/validation/resource/terraform/v1charts

COPY [".", "$WORKSPACE"]

RUN go mod init main
RUN go mod tidy
