apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "remotedialer-proxy.role" . }}
  namespace: {{ include "remotedialer-proxy.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]

