apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: {{ include "remotedialer-proxy.rolebinding" . }}
  namespace: {{ include "remotedialer-proxy.namespace" . }}
subjects:
    - kind: ServiceAccount
      name: {{ include "remotedialer-proxy.serviceAccountName" . }}
      namespace: {{ include "remotedialer-proxy.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "remotedialer-proxy.role" . }}
  apiGroup: rbac.authorization.k8s.io
