FROM registry.suse.com/bci/golang:1.19

# Configure Go
ENV GOPATH /root
ENV PATH ${PATH}:/root/bin

ENV WORKSPACE ${GOPATH}/src/github.com/rancher/rancher
ENV WORKSPACE2 ${GOPATH}/src/github.com/rancherlabs/corral-packages

WORKDIR $WORKSPACE

COPY ["./rancher", "$WORKSPACE"]
COPY ["./corral-packages", "$WORKSPACE2"]

ENV CORRAL_VERSION="v1.1.1"

RUN mkdir -p /root/.ssh
RUN cp ${WORKSPACE}/tests/v2/validation/.ssh/jenkins-* /root/.ssh
RUN chmod 600 /root/.ssh/jenkins-*
RUN ssh-keygen -f /root/.ssh/jenkins-* -y > /root/.ssh/id_rsa.pub

RUN zypper -n install gcc binutils glibc-devel-static ca-certificates git-core wget curl unzip tar vim less file xz gzip sed gawk iproute2 iptables jq
RUN zypper install -y -f docker && rpm -e --nodeps --noscripts containerd
RUN go mod download && \
    go install gotest.tools/gotestsum@latest && \
    go install github.com/rancherlabs/corral@${CORRAL_VERSION}