name: "Build Rancher Agent"
description: "Build and upload the Rancher agent image"
runs:
  using: "composite"
  steps:
    - name: Arch environment variable
      shell: bash
      run: |
        if [[ "$ARCH" == "x64" ]]; then
          echo "ARCH=amd64" >> $GITHUB_ENV
        fi
    - name: install yq
      uses: ./.github/actions/install-yq
      with:
        arch: ${{ env.ARCH }}
        use-sudo: true
    - id: env 
      name: Setup Dependencies Env Variables
      uses: ./.github/actions/setup-build-env
    - name: Setup TAG Variables
      uses: ./.github/actions/setup-tag-env
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
      with:
        images: ${{ github.repository_owner }}/rancher
        flavor: |
          latest=false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      with:
        driver-opts: network=host
    - name: Download rancher image
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: "rancher-${{ matrix.os }}-${{ env.ARCH }}"
        path: /tmp
    - name: Load image
      shell: bash
      run: |
        image_id=$(docker load --input /tmp/rancher-${{ matrix.os }}-${{ env.ARCH }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
        if [ -z "$image_id" ]; then
          echo "Error: Failed to load image from tarball!"
          exit 1
        fi
        docker tag "$image_id" ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher:${{ env.TAG }}
        docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher:${{ env.TAG }}
    - name: Build agent
      id: build
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
      with:
        push: false
        build-args: |
          "VERSION=${{ env.TAG }}"
          "ARCH=${{ env.ARCH }}"
          "RANCHER_TAG=${{ env.TAG }}"
          "REGISTRY=${{ env.REGISTRY }}"
          "RANCHER_REPO=${{ github.repository_owner }}"
          "CATTLE_RANCHER_WEBHOOK_VERSION=${{ steps.env.outputs.CATTLE_RANCHER_WEBHOOK_VERSION }}"
          "CATTLE_RANCHER_PROVISIONING_CAPI_VERSION=${{ steps.env.outputs.CATTLE_RANCHER_PROVISIONING_CAPI_VERSION }}"
        tags: ${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-${{ env.ARCH }}
        context: .
        platforms: "${{ env.OS }}/${{ env.ARCH }}"
        file: ./package/Dockerfile.agent
        labels: "${{ steps.meta.outputs.labels }}"
        outputs: type=docker,dest=/tmp/rancher-agent-${{ env.OS }}-${{ env.ARCH }}.tar
    - name: Upload image
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: "rancher-agent-${{ env.OS }}-${{ env.ARCH }}"
        path: /tmp/rancher-agent-${{ env.OS }}-${{ env.ARCH }}.tar
        if-no-files-found: error
        retention-days: 4
        overwrite: false
