name: "Build Rancher Agent"
description: "Build and upload the Rancher agent image"
runs:
  using: "composite"
  steps:
    - name: Arch environment variable
      shell: bash
      run: |
        if [[ "$ARCH" == "x64" ]]; then
          echo "ARCH=amd64" >> $GITHUB_ENV
        fi
    - id: env 
      name: Setup Dependencies Env Variables
      uses: ./.github/actions/setup-build-env
    - name: Setup TAG Variables
      uses: ./.github/actions/setup-tag-env
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
      with:
        images: ${{ github.repository_owner }}/rancher
        flavor: |
          latest=false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      with:
        driver-opts: network=host
    - name: Build agent
      id: build
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        push: false
        build-args: |
          "VERSION=${{ env.TAG }}"
          "ARCH=${{ env.ARCH }}"
          "RANCHER_REPO=${{ github.repository_owner }}"
        tags: ${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-${{ env.ARCH }}
        context: .
        platforms: "${{ env.OS }}/${{ env.ARCH }}"
        file: ./package/Dockerfile
        labels: "${{ steps.meta.outputs.labels }}"
        outputs: type=docker,dest=/tmp/rancher-agent-${{ env.OS }}-${{ env.ARCH }}.tar
        no-cache: true
        target: "agent"
    - name: Upload image
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: "rancher-agent-${{ env.OS }}-${{ env.ARCH }}"
        path: /tmp/rancher-agent-${{ env.OS }}-${{ env.ARCH }}.tar
        if-no-files-found: error
        retention-days: 4
        overwrite: false
