name: "Build Rancher Agent"
description: "Build and upload the Rancher agent image"
runs:
  using: "composite"
  steps:
    - name: Arch environment variable
      shell: bash
      run: |
        if [[ "$ARCH" == "x64" ]]; then
          echo "ARCH=amd64" >> $GITHUB_ENV
        fi
    - id: env 
      name: Setup Dependencies Env Variables
      uses: ./.github/actions/setup-build-env
    - name: Setup TAG Variables
      uses: ./.github/actions/setup-tag-env
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
      with:
        images: ${{ github.repository_owner }}/rancher
        flavor: |
          latest=false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      with:
        driver-opts: network=host
    - name: Build agent
      id: build
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
      with:
        push: false
        build-args: |
          "VERSION=${{ env.TAG }}"
          "ARCH=${{ env.ARCH }}"
          "RANCHER_REPO=${{ github.repository_owner }}"
          "CATTLE_RANCHER_WEBHOOK_VERSION=${{ steps.env.outputs.CATTLE_RANCHER_WEBHOOK_VERSION }}"
          "CATTLE_RANCHER_TURTLES_VERSION=${{ steps.env.outputs.CATTLE_RANCHER_TURTLES_VERSION }}"
        tags: ${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-${{ env.ARCH }}
        context: .
        platforms: "${{ env.OS }}/${{ env.ARCH }}"
        file: ./package/Dockerfile
        labels: "${{ steps.meta.outputs.labels }}"
        outputs: type=docker,dest=/tmp/rancher-agent-${{ env.OS }}-${{ env.ARCH }}.tar
        no-cache: true
        target: "agent"
    - name: Upload image
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: "rancher-agent-${{ env.OS }}-${{ env.ARCH }}"
        path: /tmp/rancher-agent-${{ env.OS }}-${{ env.ARCH }}.tar
        if-no-files-found: error
        retention-days: 4
        overwrite: false
