name: "Build Rancher Server"
description: "Build and upload the Rancher server image"
runs:
  using: "composite"
  steps:
    - name: Arch environment variable
      shell: bash
      run: |
        if [[ "$ARCH" == "x64" ]]; then
          echo "ARCH=amd64" >> $GITHUB_ENV
        fi
    - name: install yq
      uses: ./.github/actions/install-yq
      with:
        arch: ${{ env.ARCH }}
        use-sudo: true
    - name: Setup Environment Variables
      uses: ./.github/actions/setup-tag-env
    - id: env 
      name: Setup Dependencies Env Variables
      uses: ./.github/actions/setup-build-env
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository_owner }}/rancher
        flavor: |
          latest=false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Create k3s images file
      uses: ./.github/actions/k3s-images
      with:
        k3s_version: ${{ steps.env.outputs.CATTLE_K3S_VERSION }}
    - name: Download data.json
      shell: bash
      run: curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${{ steps.env.outputs.CATTLE_KDM_BRANCH }}/data.json > ./data.json
    - name: Build and export server
      id: build
      uses: docker/build-push-action@v5
      with:
        push: false
        build-args: |
          "VERSION=${{ env.TAG }}"
          "COMMIT=${{ env.COMMIT }}"
          "RKE_VERSION=${{ steps.env.outputs.RKE_VERSION }}"
          "ARCH=${{ env.ARCH }}"
          "CATTLE_RANCHER_WEBHOOK_VERSION=${{ steps.env.outputs.CATTLE_RANCHER_WEBHOOK_VERSION }}"
          "CATTLE_RANCHER_PROVISIONING_CAPI_VERSION=${{ steps.env.outputs.CATTLE_RANCHER_PROVISIONING_CAPI_VERSION }}"
          "CATTLE_CSP_ADAPTER_MIN_VERSION=${{ steps.env.outputs.CATTLE_CSP_ADAPTER_MIN_VERSION }}"
          "CATTLE_FLEET_VERSION=${{ steps.env.outputs.CATTLE_FLEET_VERSION }}"
        tags: ${{ github.repository_owner }}/rancher:${{ env.TAG }}-${{ env.ARCH }}
        context: .
        platforms: "${{ env.OS }}/${{ env.ARCH }}"
        file: ./package/Dockerfile
        labels: "${{ steps.meta.outputs.labels }}"
        outputs: type=docker,dest=/tmp/rancher-${{ env.OS }}-${{ env.ARCH }}.tar
        no-cache: true
        target: "server"
    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: "rancher-${{ env.OS }}-${{ env.ARCH }}"
        path: /tmp/rancher-${{ env.OS }}-${{ env.ARCH }}.tar
        if-no-files-found: error
        retention-days: 4
        overwrite: false
