#!/bin/bash
set -e

# Port-forward to the registry cache pod so we can push images to it
echo "Starting port-forward to registry-cache"
kubectl port-forward registry-cache 5000:5000 > /dev/null &
pf_pid=$!

# Kill the port-forward on exit
cleanup() {
  echo "Killing port-forward to registry-cache"
  kill $pf_pid
}

trap cleanup exit

# Wait for the port-forward to take effect
./scripts/await "curl -u admin:admin -k -o /dev/null https://localhost:5000/v2/_catalog"

# Use skopeo to copy images from internal Docker registry to the registry in the cluster
images=(
  "rancher/rancher-agent:master-head"
)

for image in "${images[@]}"; do
  skopeo copy --dest-tls-verify=false --dest-creds=admin:admin docker-daemon:$image docker://localhost:5000/$image
done
