name: "Generate images digests"
description: "Setup and generate images digests"
runs:
  using: "composite"
  steps:
    - name: install dependencies
      shell: bash
      run: zypper install -y aws-cli wget jq awk
    - name: install gh
      shell: bash
      run: |
        mkdir -p /tmp/gh
        curl -fsL https://github.com/cli/cli/releases/download/v${{ env.GH_CLI_VERSION }}/gh_${{ env.GH_CLI_VERSION }}_linux_amd64.tar.gz | tar xvzf - --strip-components=1 -C /tmp/gh
        mv /tmp/gh/bin/gh /usr/bin/gh
        chmod +x /usr/bin/gh
    - name: Setup Environment Variables
      uses: ./.github/actions/setup-tag-env
    - name: Setup ecm-distro-tools
      uses: rancher/ecm-distro-tools@v0.49.1
    - name: Create base dir
      shell: bash
      run: mkdir -p "$ARTIFACTS_BASE_DIR"
    - name: Generate linux docker digests
      shell: bash
      run: |
        export LINUX_IMAGES_URL=https://github.com/${{ github.repository }}/releases/download/${{ env.TAG }}/rancher-images.txt
        release generate rancher docker-images-digests --config "{}" --registry "${{ env.REGISTRY }}" --images-url "${LINUX_IMAGES_URL}" --output-file "$ARTIFACTS_BASE_DIR/$LINUX_FILE"
    - name: Generate windows docker digests
      shell: bash
      run: |
        export WINDOWS_IMAGES_URL=https://github.com/${{ github.repository }}/releases/download/${{ env.TAG }}/rancher-windows-images.txt
        release generate rancher docker-images-digests --config "{}" --registry "${{ env.REGISTRY }}" --images-url "${WINDOWS_IMAGES_URL}" --output-file "$ARTIFACTS_BASE_DIR/$WINDOWS_FILE"
    - name: Generate sha256sum file
      shell: bash
      env:
        ARTIFACTS_TYPE: "digests"
      run: scripts/artifacts-hashes.sh
