name: "Build Rancher Installer"
description: "Build and upload the Rancher installer image"
runs:
  using: "composite"
  steps:
    - name: Environment variables
      shell: bash
      run: |
        if [[ "$ARCH" == "x64" ]]; then
          echo "ARCH=amd64" >> $GITHUB_ENV
        fi
    - name: Setup Environment Variables
      uses: $/.github/actions/setup-tag-env
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
      with:
        images: ${{ github.repository_owner }}/system-agent-installer-rancher
        flavor: |
          latest=false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
    - name: Build and export installer image
      id: build-installer
      uses: docker/bake-action@018cb6412ab401ebaa809aa5f85966b74628600f # v7.4.0
      env:
        REPO: ${{ github.repository_owner }}
        DEST_DIR: /tmp
      with:
        files: |
          ./docker-bake.hcl
          cwd://${{ steps.meta.outputs.bake-file-labels }}
        targets: installer
    - name: Upload installer image
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: "rancher-installer-${{ env.OS }}-${{ env.ARCH }}"
        path: /tmp/system-agent-installer-rancher-${{ env.OS }}-${{ env.ARCH }}.tar
        if-no-files-found: error
        retention-days: 4
        overwrite: false
