FROM python:3.7.0

ARG KUBECTL_VERSION=v1.14.7
ENV WORKSPACE /src/rancher-validation
WORKDIR $WORKSPACE
ENV PYTHONPATH /src/rancher-validation
ARG RKE_VERSION=v0.2.8

COPY [".", "$WORKSPACE"]

RUN wget https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl && \
    mv kubectl /bin/kubectl && \
    chmod +x /bin/kubectl  && \
    wget https://github.com/rancher/rke/releases/download/$RKE_VERSION/rke_linux-amd64 && \
    mv rke_linux-amd64 /bin/rke && \
    chmod +x /bin/rke && \
    wget https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz && \
    tar -x -f helm-v3.0.2-linux-amd64.tar.gz && \
    mv linux-amd64/helm /bin/helm_v3 && \
    chmod +x /bin/helm_v3 && \
    cd $WORKSPACE && \
    pip install -r requirements_v3api.txt