#!/usr/bin/env bash

set -e

echo "-- chart/index --"

cd $(dirname $0)/../..
repo_index=${1}

# Do not merge the repo index if it is a release repo.
# These repos contain only the latest version of the chart.
if [[ "${repo_index}" =~ "release-" ]]; then
  helm_v3 repo index ./bin/chart/${repo_index}
else
  mkdir -p build

  echo "Getting current index from ${repo_index}"
  # Using the s3 URL mitigates cache issues when building multiple charts in parallel
  curl -f "https://s3.amazonaws.com/charts.optimus.rancher.io/server-charts/${repo_index}/index.yaml" -o build/index.yaml

  helm_v3 repo index --merge build/index.yaml ./bin/chart/${repo_index}
fi
