#!/usr/bin/env bash

set -e

echo "-- chart/package --"

cd $(dirname $0)/..
. ./version

mkdir -p ../bin/chart/${CHART_REPO}

helm_v3 package -d ../bin/chart/${CHART_REPO} ../build/chart/rancher

echo "updating index ... "
./chart/index ${CHART_REPO}
