#!/usr/bin/env bash

echo "-- chart/test --"

# Check for helm_v3
if [ -z "$(type -p helm_v3)" ]; then
    echo "helm_v3 not found. Helm is required to run tests."
    exit 1
fi

# Check for unittest plugin
HELM_PLUGINS=/root/.local/share/helm/plugins/ helm_v3 unittest --help >/dev/null 2>&1
if [[ $? > 0 ]]; then
    echo "helm_v3 plugin unittest not found."
    echo "Run to install plugin: helm_v3 plugin install https://github.com/helm-unittest/helm-unittest"
    exit 1
fi

HELM_PLUGINS=/root/.local/share/helm/plugins/ helm_v3 unittest --helm3 ../../build/chart/rancher
