#!/usr/bin/env bash

echo "-- chart/validate --"

# Check for helm
hash helm >/dev/null 2>&1
if [[ $? > 0 ]]; then
    echo "helm not found. Helm is required to run tests."
    exit 1
fi

helm lint ../../build/chart/rancher
