#!/usr/bin/env bash

set -ex

echo "-- chart/validate --"

# Check for helm
if [ -z "$(type -p helm_v3)" ]; then
    echo "helm_v3 not found. Helm is required to run tests."
    exit 1
fi

helm_v3 lint $(dirname $0)/../../build/chart/rancher
