#!/usr/bin/env bash

echo "-- chart/validate --"

# Check for helm
hash helm >/dev/null 2>&1
if [[ $? > 0 ]]; then
    echo "helm not found. Helm is required to run tests."
    exit 1
fi

if which helm_v3 >/dev/null 2>&1
then
    helm_v3 lint ../../build/chart/rancher
else
    helm lint ../../build/chart/rancher
fi
