// Code generated by pkg/codegen/config/main.go. DO NOT EDIT.
// Package buildconfig contains a set of exported constants that represent configuration variables of Rancher at build-time.
package buildconfig

const (
	ChartDefaultBranch       = "dev-v2.9"
	CspAdapterMinVersion     = "103.0.0+up3.0.0"
	DefaultShellVersion      = "rancher/shell:v0.1.22"
	FleetVersion             = "104.0.0+up0.10.0-rc.4"
	KdmBranch                = "dev-v2.9"
	SystemChartDefaultBranch = "dev-v2.9"
	WebhookVersion           = "104.0.0+up0.5.0-rc6"
)
