// Code generated by pkg/codegen/config/main.go. DO NOT EDIT.
// Package buildconfig contains a set of exported constants that represent configuration variables of Rancher at build-time.
package buildconfig

const (
	CspAdapterMinVersion = "103.0.1+up3.0.1"
	DefaultShellVersion  = "rancher/shell:v0.1.23"
	FleetVersion         = "103.1.4+up0.9.4-rc.1"
	WebhookVersion       = "103.0.2+up0.4.3"
)
