// Code generated by pkg/codegen/config/main.go. DO NOT EDIT.
// Package buildconfig contains a set of exported constants that represent configuration variables of Rancher at build-time.
package buildconfig

const (
	CspAdapterMinVersion    = "105.0.0+up5.0.1"
	DefaultShellVersion     = "rancher/shell:v0.3.0"
	FleetVersion            = "105.0.2+up0.11.2"
	ProvisioningCAPIVersion = "105.1.0+up0.6.0"
	WebhookVersion          = "105.0.0+up0.6.1"
)
