FROM golang:1.17

# Configure Go
ENV GOPATH /go
ENV PATH ${PATH}:/go/bin

ENV WORKSPACE ${GOPATH}/src/github.com/rancher/rancher

WORKDIR $WORKSPACE/tests/v2/validation/resource/terraform/v2charts

COPY [".", "$WORKSPACE"]
RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x ./kubectl \
    && mv ./kubectl /go/bin

RUN go mod init main
RUN go get github.com/hashicorp/terraform-exec/tfexec@v0.17.2
RUN go get github.com/hashicorp/hc-install@v0.4.0
RUN go mod tidy
