#!/bin/bash

apt-get update -q
apt-get install -y python-dev python-pip python-tox libyaml-dev

pip install -U pip tox virtualenv
curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
