#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"

BINARY="agent-$PROG"

CGO_ENABLED=0 go build -tags k8s \
    -ldflags \
    "-X github.com/rancher/rancher/pkg/version.Program=$BINARY
     -X main.VERSION=$VERSION $LINKFLAGS" \
    -o bin/$BINARY ./cmd/agent
