#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
cd ./cmd/rancherd

K8S_VERSION=$(grep 'ARG RKE2_VERSION=' ../../package/Dockerfile.runtime | sed 's/.*RKE2_VERSION=//')
go build -o ../../bin/rancherd-${ARCH} \
    -ldflags '-extldflags "-static"
    -X github.com/rancher/rke2/pkg/images.KubernetesVersion='$K8S_VERSION'-'$ARCH'
    -X github.com/rancher/rke2/pkg/images.RuntimeImageName=rancher-runtime
    -X github.com/rancher/k3s/pkg/version.Program=rke2
    -X github.com/rancher/k3s/pkg/version.Version='$TAG \
    -tags "netgo osusergo "
if [ "$ARCH" = "amd64" ]; then
    cp ../../bin/rancherd-${ARCH} ../../bin/rancherd
fi

cd ../..
./scripts/chart/build cmd/rancherd/chart
./scripts/chart/package

sed -e "s|%{CHART_CONTENT}%|$(base64 -w0 ./bin/chart/*/rancher-${CHART_VERSION}.tgz)|g" ./scripts/rancher.yaml.tmpl > ./bin/rancher.yaml
