#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"

BINARY="agent-${PROG}"

if [ -z "${GODEBUG}" ]; then
    EXTRA_LDFLAGS="${EXTRA_LDFLAGS} -w"
    DEBUG_GO_GCFLAGS=""
    DEBUG_TAGS=""
else
    DEBUG_GO_GCFLAGS='-gcflags=all=-N -l'
fi

BUILDTAGS="k8s netgo osusergo no_stage static_build"
CGO_ENABLED=1 go build \
    -tags "${BUILDTAGS}" ${GO_GCFLAGS} ${GO_BUILD_FLAGS} \
    -ldflags \
    "-X github.com/rancher/rancher/pkg/version.Program=${BINARY}
     -X main.VERSION=${VERSION} ${LINKFLAGS}" \
    -o bin/${BINARY} ./cmd/agent
