#!/bin/bash
if [ "x${RELEASE_ACTION}" = "x" ]; then
    echo "RELEASE_ACTION is not set, needs to be 'release' or 'revert'"
    exit 1
fi

case $RELEASE_ACTION in
  release)
    CURRENT_BRANCH="dev-v2.7"
    NEW_BRANCH="release-v2.7"
    ;;
  revert)
    CURRENT_BRANCH="release-v2.7"
    NEW_BRANCH="dev-v2.7"
    ;;
  *)
    echo "Not a valid RELEASE_ACTION (${RELEASE_ACTION}), needs to be 'release' or 'revert'"
    exit 1
esac

echo "RELEASE_ACTION is ${RELEASE_ACTION}"
echo "Going to change ${CURRENT_BRANCH} to ${NEW_BRANCH}"

# scripts/package-env
for PKGENV in SYSTEM_CHART_DEFAULT_BRANCH CHART_DEFAULT_BRANCH; do
   sed -i "/^${PKGENV}/ s/${CURRENT_BRANCH}/${NEW_BRANCH}/" scripts/package-env
done

# package/Dockerfile
for DFARG in SYSTEM_CHART_DEFAULT_BRANCH CHART_DEFAULT_BRANCH CATTLE_KDM_BRANCH; do
   sed -i "/ARG ${DFARG}/ s/${CURRENT_BRANCH}/${NEW_BRANCH}/" package/Dockerfile
done

# Dockerfile.dapper
for DFDENV in CATTLE_KDM_BRANCH; do
   sed -i "/ENV ${DFDENV}/ s/${CURRENT_BRANCH}/${NEW_BRANCH}/" Dockerfile.dapper
done

# pkg/settings/setting.go
for PKGSETTING in KDMBranch ChartDefaultBranch; do
   sed -i "/${PKGSETTING}/ s/${CURRENT_BRANCH}/${NEW_BRANCH}/" pkg/settings/setting.go
done

echo "Done changing values"
