#!/bin/bash
# Without RELEASE_TYPE set, it will show the values for each.
# With RELEASE_TYPE set to 'rc' or 'final-rc', it will compare the values to the expected ones and report CORRECT or INCORRECT

case $RELEASE_TYPE in
  rc)
    REQUIRED_VALUE="dev-v2.9"
    ;;
  final-rc)
    REQUIRED_VALUE="release-v2.9"
    ;;
esac

if [ -n "${RELEASE_TYPE}" ]; then
   echo "RELEASE_TYPE is ${RELEASE_TYPE}"
   echo "Going to check for ${REQUIRED_VALUE}"
fi

# build.yaml
for value in systemChartDefaultBranch chartDefaultBranch kdmBranch; do
   FOUND_VALUE=$(grep ^${value} build.yaml | awk -F': ' '{ print $2 }')
   if [ -n "${RELEASE_TYPE}" ]; then
      echo -n "${value}: ${FOUND_VALUE} in build.yaml: "
      if [ "${FOUND_VALUE}" != "${REQUIRED_VALUE}" ]; then
        echo "INCORRECT (should be ${REQUIRED_VALUE})"
      else
        echo "CORRECT"
      fi
   else
      echo "* ${value}: ${FOUND_VALUE} (\`build.yaml\`)"
   fi
done
