#!/bin/bash
set -e
cd $(dirname $0)

if  [ -n "$CATTLE_KDM_BRANCH" ]; then
    curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${CATTLE_KDM_BRANCH}/data.json > ../bin/data.json
elif [ ! -e ../bin/data.json ] && [ -e ../kontainer-driver-metadata/data/data.json ]; then
    cp ../kontainer-driver-metadata/data/data.json ../bin/data.json
fi

source version
source package-env

cd ../package
../scripts/k3s-images.sh

cp ../bin/data.json ../bin/rancher-data.json

cd ../bin

if [ ! -d $CHART_REPO_DIR ]; then
    git clone --branch $CHART_DEFAULT_BRANCH https://github.com/rancher/charts $CHART_REPO_DIR
fi

CHARTS_DIRS="${CHARTS_DIRS:+${CHARTS_DIRS},}${CHART_REPO_DIR}"

TAG=$TAG REPO=${REPO} go run ../pkg/image/origins/main.go $CHARTS_DIRS $IMAGE $AGENT_IMAGE $SYSTEM_AGENT_UPGRADE_IMAGE $WINS_AGENT_UPGRADE_IMAGE $CLUSTER_API_CONTROLLER_IMAGE ${SYSTEM_AGENT_INSTALLER_RKE2_IMAGES[@]} ${SYSTEM_AGENT_INSTALLER_K3S_IMAGES[@]}
