#!/bin/bash

# Copyright (C) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

set -e

cd $(dirname $0)

./build
./package
./chart/ci
