#!/bin/bash
set -e

cd $(dirname $0)

if ./only-ui-bumps.sh; then
    ./build
    ./package
    ./chart/ci
    exit 0
fi

echo "cleaning Go cache"
go env GOCACHE
echo "==="
ls -lha $(go env GOCACHE)
echo "==="
go clean -cache
ls -lha $(go env GOCACHE)

#./validate
./build
./package
./test
./chart/ci
