#!/usr/bin/env bash

# This is needed because it's difficult (if not impossible) to configure a GitHub Action workflow to
# pass environment variables from a file and refer to them as Docker build args.

set -e
source "$(dirname "$0")/export-config"
set -u

function replace {
  target="$1"
  echo "Replacing build-config values in $target."
  sed -i "s|\(CATTLE_RANCHER_WEBHOOK_VERSION: \).*|\1$CATTLE_RANCHER_WEBHOOK_VERSION|" "$target"
  sed -i "s|\(CATTLE_CSP_ADAPTER_MIN_VERSION: \).*|\1$CATTLE_CSP_ADAPTER_MIN_VERSION|" "$target"
  sed -i "s|\(CATTLE_FLEET_VERSION: \).*|\1$CATTLE_FLEET_VERSION|" "$target"
}

replace ".github/workflows/pull-request.yml"
replace ".github/workflows/push-release.yml"
