#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
  set -x
fi

file="$(git rev-parse --show-toplevel)/build.yaml"

export CATTLE_RANCHER_WEBHOOK_VERSION=$(grep -m1 'webhookVersion' "$file" | cut -d ' ' -f2)
export CATTLE_REMOTEDIALER_PROXY_VERSION=$(grep -m1 'remoteDialerProxyVersion' "$file" | cut -d ' ' -f2)
export CATTLE_RANCHER_PROVISIONING_CAPI_VERSION=$(grep -m1 'provisioningCAPIVersion' "$file" | cut -d ' ' -f2)
export CATTLE_CSP_ADAPTER_MIN_VERSION=$(grep -m1 'cspAdapterMinVersion' "$file" | cut -d ' ' -f2)
export CATTLE_DEFAULT_SHELL_VERSION=$(grep -m1 'defaultShellVersion' "$file" | cut -d ' ' -f2)
export CATTLE_FLEET_VERSION=$(grep -m1 'fleetVersion' "$file" | cut -d ' ' -f2)
