#!/bin/bash
set -e

source $(dirname $0)/version

echo Starting rancher server
cd $(dirname $0)/..

if [ ! -x ${SERVER_NAME} ]; then
    ./scripts/build-server
fi

rm -rf build/testdata
mkdir -p build/testdata
cd build/testdata
export KUBECONFIG=
export CATTLE_DEV_MODE=yes
export CATTLE_SERVER_URL="https://$(ip route get 8.8.8.8 | awk '{print $7}'):8443"
export CATTLE_BOOTSTRAP_PASSWORD="admin"
export CATTLE_FEATURES="harvester=false"
exec ../../${SERVER_NAME}
