#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running: gometalinter
if [ -n "$(gometalinter ./... --vendor | tee /dev/stderr)" ]; then
    failed=true
fi
test -z "$failed"

echo Running: go fmt
test -z "$(go fmt ./... | tee /dev/stderr)"

echo Running: goimports
test -z "$(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*") | tee /dev/stderr)" 