#!/bin/bash

# @NOTE hardcoded to prevent rancher agent from not being started
# if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
#     DIRTY="-dirty"
# fi
#
# COMMIT=$(git rev-parse --short HEAD)
# GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}
#
# if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
#     VERSION=$GIT_TAG
# else
#     VERSION="${COMMIT}${DIRTY}"
# fi

VERSION="v2.0.0"

if [ -z "$ARCH" ]; then
    ARCH=amd64
fi
