---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uiplugins.catalog.cattle.io
spec:
  group: catalog.cattle.io
  names:
    kind: UIPlugin
    plural: uiplugins
    singular: uiplugin
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.release.name
      name: Plugin Name
      type: string
    - jsonPath: .status.version
      name: Version
      type: string
    - jsonPath: .status.state
      name: State
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              plugin:
                properties:
                  endpoint:
                    nullable: true
                    type: string
                  metadata:
                    additionalProperties:
                      nullable: true
                      type: string
                    nullable: true
                    type: object
                  name:
                    nullable: true
                    type: string
                  noCache:
                    type: boolean
                  noAuth:
                    type: boolean
                  version:
                    nullable: true
                    type: string
                type: object
            type: object
          status:
            properties:
              cacheState:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---