FROM golang:1.20

# Configure Go
ENV GOPATH /root/go
ENV PATH ${PATH}:/root/go/bin

ENV WORKSPACE ${GOPATH}/src/github.com/rancher/rancher
# configure VPN
ARG EXTERNAL_ENCODED_VPN
ARG VPN_ENCODED_LOGIN

WORKDIR $WORKSPACE/tests/v2/validation

COPY [".", "$WORKSPACE"]

RUN go mod download && \
    go install gotest.tools/gotestsum@latest


# Configure Corral
ENV CORRAL_VERSION="v1.1.1"
RUN go install github.com/rancherlabs/corral@${CORRAL_VERSION}

RUN mkdir /root/.ssh && chmod 600 .ssh/jenkins-*
RUN ssh-keygen -f .ssh/jenkins-* -y > /root/.ssh/public.pub

RUN CGO_ENABLED=0

# necessary to run if statements using [[ ]]
SHELL ["/bin/bash", "-c"] 

RUN if [[ -z "$EXTERNAL_ENCODED_VPN" ]] ; then echo no vpn provided ; else apt-get update && \
    apt-get -y install openvpn net-tools && echo $EXTERNAL_ENCODED_VPN | base64 -d > external.ovpn && \
    if [[ -z "$VPN_ENCODED_LOGIN}" ]] ; then echo no passcode provided ; else echo adding passfile && \
    echo $VPN_ENCODED_LOGIN | base64 -d > passfile && \
    sed -i 's/auth-user-pass/auth-user-pass passfile/g' external.ovpn; fi; fi;