FROM golang:1.19

# Configure Go
ENV GOPATH /go
ENV PATH ${PATH}:/go/bin

ENV WORKSPACE ${GOPATH}/src/github.com/rancher/rancher

# Configure Terraform
ARG TERRAFORM_VERSION=0.13.7

# configure VPN
ARG EXTERNAL_ENCODED_VPN
ARG VPN_ENCODED_LOGIN

WORKDIR $WORKSPACE/tests/v2/validation

COPY [".", "$WORKSPACE"]

RUN go mod download && \
    go install gotest.tools/gotestsum@latest

RUN CGO_ENABLED=0

RUN wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && apt-get update && apt-get install unzip &&  unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip && chmod u+x terraform && mv terraform /usr/bin/terraform

# necessary to run if statements using [[ ]]
SHELL ["/bin/bash", "-c"] 

RUN if [[ -z "$EXTERNAL_ENCODED_VPN" ]] ; then echo no vpn provided ; else apt-get update && \
    apt-get -y install openvpn net-tools && echo $EXTERNAL_ENCODED_VPN | base64 -d > external.ovpn && \
    if [[ -z "$VPN_ENCODED_LOGIN}" ]] ; then echo no passcode provided ; else echo adding passfile && \
    echo $VPN_ENCODED_LOGIN | base64 -d > passfile && \
    sed -i 's/auth-user-pass/auth-user-pass passfile/g' external.ovpn; fi; fi;