// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source store.go -destination=zz_useractivity_fakes.go -package=useractivity
//

// Package useractivity is a generated GoMock package.
package useractivity
