name: rancher
summary: container management platform.
description:  an open source project that provides a container management platform built for organizations that deploy containers in production. 
  
adopt-info: rancher

grade: stable
confinement: classic

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  rancher:
    command: bin/rancher
    plugs:
      - docker
      - home
      - network
      - removable-media

parts:
  rancher:
    plugin: nil 
    source: https://github.com/rancher/rancher.git
    source-type: git
    override-pull: |
      git clone https://github.com/rancher/rancher.git src/github.com/rancher/rancher
       cd src/github.com/rancher/rancher
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/rancher/rancher
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/rancher/rancher/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/rancher/rancher/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/rancher
    build-snaps:
      - go
    build-packages:
      - git
      - sed


