name: "Publish chart to gcp"
description: "Build index and upload chart to gcp"
runs:
  using: "composite"
  steps:
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.GOOGLE_AUTH }}
    - name: Upload
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        destination: releases.rancher.com/server-charts
        path: ./bin/chart
        parent: false
        process_gcloudignore: false
        predefinedAcl: publicRead
        headers: |-
          cache-control: public,no-cache,proxy-revalidate
