name: "Publish chart to gcp"
description: "Build index and upload chart to gcp"
runs:
  using: "composite"
  steps:
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
      with:
        credentials_json: ${{ env.GOOGLE_AUTH }}
    - name: Upload
      uses: google-github-actions/upload-cloud-storage@386ab77f37fdf51c0e38b3d229fad286861cc0d0 # v2
      with:
        destination: releases.rancher.com/server-charts
        path: ./bin/chart
        parent: false
        process_gcloudignore: false
        predefinedAcl: publicRead
        headers: |-
          cache-control: public,no-cache,proxy-revalidate
