ARG PS_VERSION

FROM golang:1.12.1-windowsservercore AS build-stage
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN New-Item -Type Directory -Path '"C:\Program Files\volumeplugins"' -ErrorAction Ignore; \
    \
    Write-Host 'Downloading Volume plugins ...'; \
    \
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Invoke-WebRequest -UseBasicParsing -OutFile '"C:\Program Files\flexvolume.zip"' -Uri "https://github.com/Microsoft/K8s-Storage-Plugins/releases/download/v0.0.2/flexvolume-windows.zip"; \
    \
    Write-Host 'Expanding volumeplugins/flexvolume binaries ...'; \
    \
    Expand-Archive -Force -Path '"C:\Program Files\flexvolume.zip"' -DestinationPath '"C:\Program Files\volumeplugins"'; \
    \
    Write-Host 'Complete.';
RUN New-Item -Type Directory -Path '"C:\Program Files\nginx"' -ErrorAction Ignore; \
    \
    Write-Host 'Downloading Nginx ...'; \
    \
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Invoke-WebRequest -UseBasicParsing -OutFile '"C:\Program Files\nginx.zip"' -Uri "http://nginx.org/download/nginx-1.15.9.zip"; \
    \
    Write-Host 'Expanding Nginx binaries ...'; \
    \
    Expand-Archive -Force -Path '"C:\Program Files\nginx.zip"' -DestinationPath '"C:\Program Files\nginx"'; \
    \
    Write-Host 'Complete.';
ARG VERSION=dev
ENV AGENT_VERSION=$VERSION
COPY [".", "C:/gopath/src/github.com/rancher/rancher/"]
RUN cd C:\gopath\src\github.com\rancher\rancher; \
    \
    $env:GOARCH='amd64'; \
    $env:GOOS='windows'; \
    $env:CGO_ENABLED=0; \
    \
    Write-Host 'Building ...'; \
    \
    & .\scripts\windows\validate.ps1; \
    \
    go build -i -tags k8s -ldflags ('-X main.VERSION={0} -s -w -extldflags -static' -f $env:AGENT_VERSION) -o .\bin\agent.exe .\pkg\agent; \
    \
    if ($?) { \
        \
        .\bin\agent.exe --version; \
        \
        Write-Host 'Complete.'; \
    } else { \
        Write-Host 'Built failed.'; \
        exit 1; \
    };

FROM mcr.microsoft.com/powershell:$PS_VERSION
ENV RUN_PATH="C:\\Program Files\\rancher"
COPY --from=build-stage ["C:/Program Files/volumeplugins", "C:/Program Files/kubelet/volumeplugins"]
COPY --from=build-stage ["C:/Program Files/nginx/nginx-1.15.9/nginx.exe", "C:/Program Files/nginx/"]
COPY --from=build-stage ["C:/gopath/src/github.com/rancher/rancher/bin/agent.exe", "C:/Program Files/rancher/"]
COPY ["package/windows/*.ps1", "package/windows/*.psm1", "C:/Program Files/rancher/"]
WORKDIR $RUN_PATH
ENTRYPOINT ["pwsh.exe", "-f", "start.ps1"]

