FROM ubuntu:17.10
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates jq iproute2 && \
    curl -sLf https://get.docker.com/builds/Linux/x86_64/docker-1.10.3 > /usr/bin/docker && \
    chmod +x /usr/bin/docker && \
    DEBIAN_FRONTEND=noninteractive apt-get autoremove -y && \
    DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ARG VERSION=dev
LABEL io.cattle.agent true
ENV AGENT_IMAGE rancher/agent:${VERSION}
ENV SSL_CERT_DIR /etc/kubernetes/ssl/certs
COPY agent run.sh /usr/bin/
ENTRYPOINT ["run.sh"]
