FROM --platform=$BUILDPLATFORM registry.suse.com/bci/bci-base:16.0 AS build

RUN zypper in -y wget git

# All downloaded binaries are used at the build layer only,
# therefore they can be based off the BUILD PLATFORM architecture.
ARG BUILDARCH

ARG VERSION
ENV CHART_VERSION=${VERSION}

RUN zypper ar -f https://rpm.rancher.io/pkgs/prime pkgs && \
    rpm --import https://raw.githubusercontent.com/rancher/rancher/refs/heads/main/rancher-rpm-pkgs.key

RUN zypper in -y -r pkgs helm4 yq

RUN ln -s /usr/bin/helm4 /usr/bin/helm

WORKDIR /src
COPY .git/ /src/.git/
COPY chart/ /src/chart/
COPY scripts/ /src/scripts/
COPY build.yaml .

RUN /src/scripts/chart/ci

FROM scratch
COPY --from=build /usr/bin/helm /helm
COPY --from=build /src/bin/chart/*/*.tgz /
COPY package/installer-run.sh /run.sh
