name: "Merge images manifests"
description: "Merge docker amd64 and arm64 images manifest into a single multi-arch manifest"
inputs:
  image:
    description: "repository and image name e.g: rancher/rancher"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Environment Variables
      uses: ./.github/actions/setup-tag-env
    - name: Create manifest list and push
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        docker buildx imagetools create \
          --tag "${REGISTRY}/${IMAGE}:${TAG}" \
          "${REGISTRY}/${IMAGE}:${TAG}-amd64" \
          "${REGISTRY}/${IMAGE}:${TAG}-arm64"
    - name: Create head manifest list and push
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        if [[ "${GITHUB_REF_NAME}" == release/v* ]] || [[ "${GITHUB_REF_NAME}" == "main" ]]; then
          docker buildx imagetools create \
            --tag ${REGISTRY}/${IMAGE}:${HEAD_TAG} \
            ${REGISTRY}/${IMAGE}:${TAG}-amd64 \
            ${REGISTRY}/${IMAGE}:${TAG}-arm64
        fi
    - name: Inspect image
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        docker buildx imagetools inspect "${REGISTRY}/${IMAGE}:${TAG}"
