name: Publish Provisioning Tests Results
on:
  workflow_run:
    workflows: ["Build Pull Request"]
    types:
      - completed
permissions: {}

jobs:
  publish-provisioning-test-results:
    runs-on: runs-on,runner=4cpu-linux-x64,image=ubuntu22-full-x64,run-id=${{ github.run_id }}
    if: github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure'
    permissions:
      checks: write
      pull-requests: write
      actions: read
    steps:
      - name: mkdir test-results
        run: mkdir -p /tmp/test-results
      - name: Download All XML Test Reports
        uses: actions/download-artifact@v4
        with:
          path: /tmp/test-results/
          merge-multiple: true
          pattern: '*.xml'
      - name: Download the Event File
        uses: actions/download-artifact@v4
        with:
          path: /tmp/test-results/
          pattern: 'event.json'
      - name: debugme
        run: |
          ls -l /tmp
          ls -l /tmp/test-results/*
      - name: Publish Test Results
        uses: rancher/publish-unit-test-result-action/linux@3a74b2957438d0b6e2e61d67b05318aa25c9e6c6
        if: always()
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          event_file: /tmp/test-results/event.json
          check_run: false
          files: "/tmp/test-results/*.xml"
