name: Build Pull Request
on:
  pull_request:
    paths-ignore:
      # omit tests from triggering CI except when CI tests are changed
      - "tests/v2/codecoverage/**"
      - "tests/validation/**"

permissions:
  contents: read
  id-token: none

env:
  ARCH: amd64
  TAG: v2.14-${{ github.sha }}-head
  GIT_TAG: v2.14-${{ github.sha }}-head
  HEAD_TAG: "head"
  COMMIT: ${{ github.sha }}
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  IMAGE: ${{ github.repository_owner }}/rancher
  IMAGE_AGENT: ${{ github.repository_owner }}/rancher-agent
  IMAGE_INSTALLER: ${{ github.repository_owner }}/system-agent-installer-rancher
jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yml
  build-chart:
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: ghcr.io/rancher/ci-image/go1.26@sha256:a491bffcf6fce8e242fa2a64df51375f2d0400ddbfb7a6649365f808eb11abca # go1.26
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: setup and build
        uses: ./.github/actions/rancher-chart/build
  build-server:
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    runs-on: runs-on,runner=4cpu-${{ matrix.os }}-${{ matrix.arch }},image=ubuntu22-full-${{ matrix.arch }},run-id=${{ github.run_id }}
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.OS }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: setup and build
        uses: ./.github/actions/build-images/server
  build-agent:
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    runs-on: runs-on,runner=4cpu-${{ matrix.os }}-${{ matrix.arch }},image=ubuntu22-full-${{ matrix.arch }},run-id=${{ github.run_id }}
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.OS }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: setup and build
        uses: ./.github/actions/build-images/agent
  build-installer:
    runs-on: runs-on,runner=4cpu-linux-x64,image=ubuntu22-full-x64,run-id=${{ github.run_id }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Verify installer Dockerfile build
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: ./package/Dockerfile.installer
          build-args: |
            BUILDARCH=amd64
            VERSION=0.0.0
          platforms: linux/amd64
          load: false
          push: false
          cache-from: type=gha,scope=pr-build-installer
          cache-to: type=gha,mode=min,scope=pr-build-installer
  integration-tests:
    permissions:
      contents: read
    needs: [build-server, build-agent]
    uses: ./.github/workflows/integration-tests.yml
  provisioning-tests:
    permissions:
      contents: read
    needs: [build-server, build-agent]
    uses: ./.github/workflows/provisioning-tests.yml
