name: Rancher release
on:
  push:
    tags:
      - "v*"
      - "!v*-hotfix*"
      - "!v*-rcs*"

permissions: {}

env:
  COMMIT: ${{ github.sha }}
  DOCKERIO_REGISTRY: "docker.io"
  AWS_DEFAULT_REGION: "us-east-1"
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  IMAGE: ${{ github.repository_owner }}/rancher
  IMAGE_AGENT: ${{ github.repository_owner }}/rancher-agent
  IMAGE_INSTALLER: ${{ github.repository_owner }}/system-agent-installer-rancher
  REGISTRY: "docker.io"
jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yml
  build-server:
    runs-on: runs-on,runner=4cpu-${{ matrix.os }}-${{ matrix.arch }},image=ubuntu22-full-${{ matrix.arch }},run-id=${{ github.run_id }}
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: setup and build
        uses: ./.github/actions/build-images/server
  build-agent:
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    runs-on: runs-on,runner=4cpu-${{ matrix.os }}-${{ matrix.arch }},image=ubuntu22-full-${{ matrix.arch }},run-id=${{ github.run_id }}
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: setup and build
        uses: ./.github/actions/build-images/agent
  integration-tests:
    needs: [build-server, build-agent]
    uses: ./.github/workflows/integration-tests.yml
    permissions:
      contents: read
  push-images:
    needs: [unit-tests, integration-tests]
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    runs-on: runs-on,runner=2cpu-${{ matrix.os }}-${{ matrix.arch }},image=ubuntu22-full-${{ matrix.arch }},run-id=${{ github.run_id }}
    permissions:
      contents: read
      id-token: write
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD ;
      - name: push
        uses: ./.github/actions/push-images
  build-publish-chart:
    needs: [push-images]
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: ghcr.io/rancher/ci-image/go1.26
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: 'build-chart-tag'
      # instead of cancelling other runs, wait until they are finished
      cancel-in-progress: false
    env:
      ARCH: amd64
      REGISTRY: "" # remove to set the registry at systemDefaultRegistry on the chart
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: setup and build
        uses: ./.github/actions/rancher-chart/build
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/google-auth/rancher/credentials token | GOOGLE_AUTH ;
      - name: publish
        uses: ./.github/actions/rancher-chart/publish-gcp
  build-installer:
    runs-on: runs-on,runner=4cpu-${{ matrix.os }}-${{ matrix.arch }},image=ubuntu22-full-${{ matrix.arch }},run-id=${{ github.run_id }}
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    permissions:
      contents: read
      id-token: write
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD ;
      - name: build
        uses: ./.github/actions/build-images/installer
  merge-server-agent-installer-manifests:
    needs: [push-images, build-installer]
    runs-on: runs-on,runner=2cpu-linux-x64,image=ubuntu22-full-x64,run-id=${{ github.run_id }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD ;
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Login to Docker Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          registry: ${{ env.REGISTRY }}
      - name: merge server manifests
        with:
          image: "${{ env.IMAGE }}"
        uses: ./.github/actions/merge-manifests
      - name: merge agent manifests
        with:
          image: "${{ env.IMAGE_AGENT }}"
        uses: ./.github/actions/merge-manifests
      - name: merge installer manifests
        with:
          image: "${{ env.IMAGE_INSTALLER }}"
        uses: ./.github/actions/merge-manifests
  create-images-files:
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: ghcr.io/rancher/ci-image/go1.26:latest
    permissions:
      contents: read
    env:
      REGISTRY: ""
      ARTIFACTS_BASE_DIR: "bin"
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: generate
        uses: ./.github/actions/images-files/generate
      - name: Move files to upload directory
        shell: bash
        run: |
          set -ex
          source scripts/artifacts-list.sh

          mkdir -p /tmp/artifacts

          for artifact in "${ARTIFACTS_WITH_CHECKSUM[@]}"; do
            mv "${ARTIFACTS_BASE_DIR}/${artifact}" "/tmp/artifacts/${artifact}"
          done
      - name: "Upload artifacts"
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: images-files
          path: /tmp/artifacts
  docker-image-digests:
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: ghcr.io/rancher/ci-image/go1.26
    needs: [create-images-files, merge-server-agent-installer-manifests]
    env:
      ARTIFACTS_BASE_DIR: "dist"
      LINUX_FILE: "rancher-images-digests-linux.txt"
      WINDOWS_FILE: "rancher-images-digests-windows.txt"
      CHECKSUM_FILE: "images-digests-sha256sum.txt"
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: generate
        uses: ./.github/actions/images-digests/generate
      - name: Move files to upload directory
        shell: bash
        run: |
          set -ex
          source scripts/artifacts-list.sh

          mkdir -p /tmp/artifacts

          for artifact in "${IMAGES_DIGESTS_ARTIFACTS_WITH_CHECKSUM[@]}"; do
            mv "./${ARTIFACTS_BASE_DIR}/${artifact}" "/tmp/artifacts/${artifact}"
          done
      - name: "Upload artifacts"
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: images-digests
          path: /tmp/artifacts
  publish-artifacts:
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: ghcr.io/rancher/ci-image/go1.26
    needs: [merge-server-agent-installer-manifests, create-images-files, docker-image-digests]
    permissions:
      contents: write
      id-token: write
    env:
      ARTIFACTS_BASE_DIR: "dist"
      LINUX_FILE: "rancher-images-digests-linux.txt"
      WINDOWS_FILE: "rancher-images-digests-windows.txt"
      CHECKSUM_FILE: "images-digests-sha256sum.txt"
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Setup Environment Variables
        uses: ./.github/actions/setup-tag-env
      - name: Create artifacts dir
        shell: bash
        run: mkdir -p /tmp/artifacts
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: /tmp/artifacts
          name: images-files
          merge-multiple: true
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: /tmp/artifacts
          name: images-digests
          merge-multiple: true
      - name: Read App Secrets
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/github/app-credentials appId | APP_ID ;
            secret/data/github/repo/${{ github.repository }}/github/app-credentials privateKey | PRIVATE_KEY ;
      - name: Create App Token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        id: app-token
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.PRIVATE_KEY }}
      - name: create draft release
        shell: bash
        run: |
          set -ex
          source scripts/artifacts-list.sh

          cd /tmp/artifacts

          for artifact in "${ALL_ARTIFACTS[@]}"; do
            if [[ ! -f "${artifact}" ]]; then
              >&2 echo "missing artifact ${artifact}"
              exit 1
            fi
          done

          gh release create "${TAG}" -R "${GITHUB_REPOSITORY}" --draft --prerelease --title "${TAG}" --notes-file /tmp/artifacts/rancher-components.txt  "${ALL_ARTIFACTS[@]}"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
  notify-release:
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: ghcr.io/rancher/ci-image/go1.26
    needs: [publish-artifacts, merge-server-agent-installer-manifests, docker-image-digests]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Read App Secrets
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/slack/rancher-notify-release-bot/credentials webhookUrl | WEBHOOK_URL;
      - name: notify
        uses: ./.github/actions/notify-release
