#!/usr/bin/env bash

set -eo pipefail
set -x

source dev-scripts/prepare-build-env

BUILD_ARGS=()
BUILDX_ARGS=()
LABELS_STR="${LABELS_STR:-""}"
LABELS=()

BUILD_ACTION="${BUILD_ACTION:-"--load"}"
TARGET_PLATFORMS="${TARGET_PLATFORMS:-"${OS}/${ARCH}"}"

build_rancher() {
  DOCKER_TARGET=$1

  if [ -n "${BUILDER}" ]; then
    BUILDX_ARGS+=("--builder=${BUILDER}")
  fi

  if [ -n "${LABELS_STR}" ]; then
    temp_labels=()
    mapfile -t temp_labels <<<"$LABELS_STR"
    temp_labels=("${temp_labels[@]/#/--label=}")
    LABELS=("${LABELS[@]}" "${temp_labels[@]}")
  fi

  BUILD_ARGS+=("--build-arg=VERSION=${TAG}")
  BUILD_ARGS+=("--build-arg=COMMIT=${COMMIT}")
  BUILD_ARGS+=("--build-arg=ARCH=${ARCH}")
  BUILD_ARGS+=("--build-arg=CATTLE_RANCHER_WEBHOOK_VERSION=${CATTLE_RANCHER_WEBHOOK_VERSION}")
  BUILD_ARGS+=("--build-arg=CATTLE_REMOTEDIALER_PROXY_VERSION=${CATTLE_REMOTEDIALER_PROXY_VERSION}")
  BUILD_ARGS+=("--build-arg=CATTLE_RANCHER_TURTLES_VERSION=${CATTLE_RANCHER_TURTLES_VERSION}")
  BUILD_ARGS+=("--build-arg=CATTLE_CSP_ADAPTER_MIN_VERSION=${CATTLE_CSP_ADAPTER_MIN_VERSION}")
  BUILD_ARGS+=("--build-arg=CATTLE_FLEET_VERSION=${CATTLE_FLEET_VERSION}")
  BUILD_ARGS+=("--build-arg=CATTLE_RANCHER_PROVISIONING_CAPI_VERSION=${CATTLE_RANCHER_PROVISIONING_CAPI_VERSION}")

  docker buildx build \
    "${BUILD_ARGS[@]}" \
    "${BUILDX_ARGS[@]}" \
    "${LABELS[@]}" \
    ${BUILD_ACTION} \
    --target="${DOCKER_TARGET}" \
    --platform="${TARGET_PLATFORMS}" \
    --tag="${REPO}/rancher-linux-${ARCH}:${TAG}" \
    --file=package/Dockerfile .
}

if [ "$TARGET" = "server" ]; then
  build_rancher "server"
fi

if [ "$TARGET" = "agent" ]; then
  build_rancher "server"
fi

if [ "$TARGET" = "server-tarball" ]; then
  BUILD_ACTION=""
  BUILDX_ARGS+=("--output=type=docker,dest=/tmp/rancher-${OS}-${ARCH}.tar")
  BUILDX_ARGS+=("--no-cache")

  build_rancher "server"
fi
