#!/usr/bin/env bash

cd $(git rev-parse --show-toplevel)

check_missing() {
  var=$1
  if [ -z "${!var}" ]; then
    >&2 echo "missing var $var"
    exit 1
  fi
}

source scripts/export-config
source scripts/version

OS="${OS:-linux}"

ARCH="${ARCH:-$(uname -p)}"
if [[ "$ARCH" == "x86_64" ]]; then
  ARCH="amd64"
fi

REPO_OWNER="${REPO_OWNER:-"rancher"}"
IMAGE="${IMAGE:-"$REPO_OWNER/rancher"}"
IMAGE_AGENT="${IMAGE_AGENT:-"$REPO_OWNER/rancher-agent"}"
IMAGE_INSTALLER="${IMAGE_INSTALLER:-"$REPO_OWNER/system-agent-installer-rancher"}"
CATTLE_KDM_BRANCH=$(grep -m1 'ARG CATTLE_KDM_BRANCH=' package/Dockerfile | cut -d '=' -f2)
CATTLE_K3S_VERSION=$(grep -m1 'ENV CATTLE_K3S_VERSION=' package/Dockerfile | cut -d '=' -f2)
HELM_VERSION=$(grep -m1 'ENV HELM_VERSION=' package/Dockerfile.installer | cut -d '=' -f2)
GO_VERSION=$(grep -m1 'golang:' package/Dockerfile | cut -d ':' -f2 | cut -d ' ' -f1)
HELM_UNITTEST_VERSION=$(grep -m1 'ENV HELM_UNITTEST_VERSION=' Dockerfile.dapper | cut -d '=' -f2)
CATTLE_HELM_VERSION=$(grep -m1 'ENV CATTLE_HELM_VERSION=' package/Dockerfile | cut -d '=' -f2)

export ARCH=$ARCH
export OS=$OS
export REPO=$REPO
export REPO_OWNER=$REPO_OWNER
export IMAGE=$IMAGE
export IMAGE_AGENT=$IMAGE_AGENT
export IMAGE_INSTALLER=$IMAGE_INSTALLER
export CATTLE_KDM_BRANCH=$CATTLE_KDM_BRANCH
export CATTLE_K3S_VERSION=$CATTLE_K3S_VERSION
export HELM_VERSION=$HELM_VERSION
export GO_VERSION=$GO_VERSION
export HELM_UNITTEST_VERSION=$HELM_UNITTEST_VERSION
export CATTLE_HELM_VERSION=$CATTLE_HELM_VERSION

check_missing "ARCH"
check_missing "OS"
check_missing "REPO"
check_missing "IMAGE"
check_missing "IMAGE_AGENT"
check_missing "IMAGE_INSTALLER"
check_missing "CATTLE_KDM_BRANCH"
check_missing "CATTLE_K3S_VERSION"
check_missing "HELM_VERSION"
check_missing "GO_VERSION"
check_missing "HELM_UNITTEST_VERSION"
check_missing "CATTLE_HELM_VERSION"
check_missing "CATTLE_RANCHER_WEBHOOK_VERSION"
check_missing "CATTLE_REMOTEDIALER_PROXY_VERSION"
check_missing "CATTLE_RANCHER_TURTLES_VERSION"
check_missing "CATTLE_CSP_ADAPTER_MIN_VERSION"
check_missing "CATTLE_FLEET_VERSION"
check_missing "REGISTRY"
check_missing "TAG"
check_missing "COMMIT"
